---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jh.
--- DateTime: 2024/7/11 16:42
---
if (redis.call('get', KEYS[1]) == ARGV[1]) then
    -- 释放锁
    return redis.call('del', KEYS[1])
end
return 0